# Generated by Django 5.2 on 2025-04-16 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('min_hours', models.IntegerField(blank=True, default=5, help_text="Enter the 'minimum working hour' as an integer in range [0,50]. (Default: 5)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('max_hours', models.IntegerField(blank=True, default=20, help_text="Enter the 'maximum working hour' as an integer in range [0,50] (Default: 20)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('preferability', models.IntegerField(blank=True, default=1, help_text="Enter the 'preferability' as an integer in range [0,2]. (Default: 1)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
    ]
